---
    - name: Upload .tar.gz file containing binaries from local storage
      copy:
        src: "kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/kibana_64.tar.gz"
      register: download_kibana
      until: download_kibana is succeeded
      tags: upkibana
    - name: Ensure installation dir exists
      become: true
      file:
        state: directory
        path: "{{ kibana_home }}"
      tags: dirkibana
    - name: Extract Kibana in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/kibana_64.tar.gz"
        dest: "{{ kibana_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ kibana_home }}/bin/kibana"
      tags: unkibana
